# Generated by Django 5.1.3 on 2024-11-19 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_courses_end_date_alter_courses_start_date'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='students',
            field=models.ManyToManyField(blank=True, null=True, related_name='courses', to='students.students'),
        ),
    ]
