# Generated by Django 5.1.3 on 2024-11-18 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='end_date',
            field=models.DateField(blank=True, verbose_name='Дата окончания курса'),
        ),
        migrations.AlterField(
            model_name='courses',
            name='start_date',
            field=models.DateField(blank=True, verbose_name='Дата начала курса'),
        ),
    ]
